### ISSUE TITLE
Build failure with `template-haskell-2.17`, bound not revisable on hackage

### ISSUE THREAD

**Issue by andreasabel** [jvranish/Lenses#3]
Build with GHC 9.0 fails because of a change in `template-haskell` (see below).
A bound `template-haskell < 2.17` would be necessary for the versions already released on hackage.
Unfortunately, `template-haskell` is only a `build-depends` in conditionals in the cabal file and those cannot be revised.
(Due to this limitation, it is best practice to mention all dependencies in an unconditional `build-depends`, and add additional constraints on these dependencies in the conditionals.)
```
$ cabal install lenses

Build profile: -w ghc-9.0.1 -O1
In order, the following will be built (use -v for more details):
 - lenses-0.1.8 (lib:lenses) (requires build)
...
[2 of 2] Compiling Data.Lenses.Template ( src-26/Data/Lenses/Template.hs, dist/build/Data/Lenses/Template.o, dist/build/Data/Lenses/Template.dyn_o )

src-26/Data/Lenses/Template.hs:110:18: error:
    • Expecting one more argument to ‘TyVarBndr’
      Expected a type, but ‘TyVarBndr’ has kind ‘* -> *’
    • In the type signature:
        makeAccs :: [TyVarBndr] -> [VarStrictType] -> Q [Dec]
      In an equation for ‘nameDeriveLenses’:
...
```
